#ifndef MAGICNUMBER_H
#define MAGICNUMBER_H

#define SUCCESS 0
#define FAILURE 1
#define EXIT_SUCCESS 0
#define EXIT_FAILURE 1
#define GETHOSTNAME_FAILURE -1
#define HOSTNAME_MAX_LENGTH 64
#define SOCKET_FAILURE -1
#define FCNTL_FAILURE -1
#define BIND_FAILURE -1
#define LISTEN_FAILURE -1
#define DEFAULT_SOCKET_PROTOCOL 0
#define POLL_FAILURE -1
#define NICK_MAX_LENGTH_RFC2812 9

#endif
